# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evalCoverage <- function(pos, width, sampleID, length, minOverlap, minContigLength, nrOfSamples, plotCoverage) {
    .Call(`_MGCS_evalCoverage`, pos, width, sampleID, length, minOverlap, minContigLength, nrOfSamples, plotCoverage)
}

getIdenticalSeqs <- function(starts1, ends1, starts2, ends2, nm1, nm2, minL = 0L) {
    .Call(`_MGCS_getIdenticalSeqs`, starts1, ends1, starts2, ends2, nm1, nm2, minL)
}

getIdenticalSeqsList <- function(names1, starts1, ends1, names2, starts2, ends2, minL = 0L) {
    .Call(`_MGCS_getIdenticalSeqsList`, names1, starts1, ends1, names2, starts2, ends2, minL)
}

makeChimericContigs <- function(seqNames, covs, covVecs, starts, ends, seqs, ovStarts1, ovEnds1, ovStarts2, ovEnds2, namesOv, seqID1, seqID2, minShare, onlyInvisibleChimeric) {
    .Call(`_MGCS_makeChimericContigs`, seqNames, covs, covVecs, starts, ends, seqs, ovStarts1, ovEnds1, ovStarts2, ovEnds2, namesOv, seqID1, seqID2, minShare, onlyInvisibleChimeric)
}

isNeccessary <- function(thisName1, thisName2, name1, name2) {
    .Call(`_MGCS_isNeccessary`, thisName1, thisName2, name1, name2)
}

makeFastaOutput <- function(names, seqs, outFile) {
    .Call(`_MGCS_makeFastaOutput`, names, seqs, outFile)
}

sequenceToFastaReads <- function(starts, sequence, meanWidth, newFasta, nameTag) {
    .Call(`_MGCS_sequenceToFastaReads`, starts, sequence, meanWidth, newFasta, nameTag)
}

calcMinOverlap <- function(seq, meanWidth) {
    .Call(`_MGCS_calcMinOverlap`, seq, meanWidth)
}

subSeqs <- function(seq, starts, ends) {
    .Call(`_MGCS_subSeqs`, seq, starts, ends)
}

calcCovVec <- function(readsPerSample, lengths) {
    .Call(`_MGCS_calcCovVec`, readsPerSample, lengths)
}

